replace hard-coding with variables

diff --git a/scripts/run_all b/scripts/run_all
--- a/scripts/run_all
+++ b/scripts/run_all
@@ -29,23 +29,23 @@ TIME_SECONDS=$((TIME_MINUTE * 60))
 # Confirm the directory to save results
 echo "Results directory: ${RESULT_DIR}"
 
-## Fuzing options
-#if [ "${SUBJECT}" = "lightftp" ]; then
-#  AFLNET_OPTIONS='"-P FTP -D 10000 -q 3 -s 3 -E -K -c ./ftpclean.sh"'
-#  LEGION_OPTIONS='"-P FTP -D 10000 -q 4 -s 4 -E -K -c ./ftpclean.sh"'
-#elif  [ "${SUBJECT}" = "proftpd" ]; then
-#  AFLNET_OPTIONS="-t 1000+ -m none -P FTP -D 10000 -q 3 -s 3 -E -K -c clean"
-#  LEGION_OPTIONS="-t 1000+ -m none -P FTP -D 10000 -q 4 -s 4 -E -K -c clean"
-#elif  [ "${SUBJECT}" = "openssl" ]; then
-#  AFLNET_OPTIONS='"-P TLS -D 10000 -q 3 -s 3 -E -K -R -W 100"'
-#  LEGION_OPTIONS='"-P TLS -D 10000 -q 4 -s 4 -E -K -R -W 100"'
-#elif  [ "${SUBJECT}" = "openssh" ]; then
-#  AFLNET_OPTIONS='"-P SSH -D 10000 -q 3 -s 3 -E -K -W 10"'
-#  LEGION_OPTIONS='"-P SSH -D 10000 -q 4 -s 4 -E -K -W 10"'
-#else
-#  echo "Invalid subject: ${SUBJECT}"
-#  exit 1
-#fi
+# Fuzing options
+if [ "${SUBJECT}" = "lightftp" ]; then
+  AFLNET_OPTIONS=\""-P FTP -D 10000 -q 3 -s 3 -E -K -c ./ftpclean.sh"\"
+  LEGION_OPTIONS=\""${LEGION_PARAMS} -P FTP -D 10000 -q 4 -s 4 -E -K -c ./ftpclean.sh"\"
+elif  [ "${SUBJECT}" = "proftpd" ]; then
+  AFLNET_OPTIONS=\""-t 1000+ -m none -P FTP -D 10000 -q 3 -s 3 -E -K -c clean"\"
+  LEGION_OPTIONS=\""${LEGION_PARAMS} -t 1000+ -m none -P FTP -D 10000 -q 4 -s 4 -E -K -c clean"\"
+elif  [ "${SUBJECT}" = "openssl" ]; then
+  AFLNET_OPTIONS=\""-P TLS -D 10000 -q 3 -s 3 -E -K -R -W 100"\"
+  LEGION_OPTIONS=\""${LEGION_PARAMS} -P TLS -D 10000 -q 4 -s 4 -E -K -R -W 100"\"
+elif  [ "${SUBJECT}" = "openssh" ]; then
+  AFLNET_OPTIONS=\""-P SSH -D 10000 -q 3 -s 3 -E -K -W 10"\"
+  LEGION_OPTIONS=\""${LEGION_PARAMS} -P SSH -D 10000 -q 4 -s 4 -E -K -W 10"\"
+else
+  echo "Invalid subject: ${SUBJECT}"
+  exit 1
+fi
 
 # Make sure the result folder exists
 mkdir -p "${RESULT_DIR}"
@@ -53,50 +53,52 @@ mkdir -p "${RESULT_DIR}"
 # Run fuzzing
 ## Confirm the experiment duration
 echo "Fuzzing time: ${TIME_SECONDS} seconds"
+echo "Legion options: ${LEGION_OPTIONS}"
 if [ "${ONLY_LEGION}" -eq "0" ]; then
-  if [ "${SUBJECT}" = "lightftp" ]; then
-    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet out-"${SUBJECT}"-aflnet "-P FTP -D 10000 -q 3 -s 3 -E -K -c ./ftpclean.sh" "${TIME_SECONDS}" 5 &
-    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -P FTP -D 10000 -q 4 -s 4 -E -K -c ./ftpclean.sh" "${TIME_SECONDS}" 5 &
-    wait
-  elif [ "${SUBJECT}" = "proftpd" ]; then
-    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet out-"${SUBJECT}"-aflnet "-t 1000+ -m none -P FTP -D 10000 -q 3 -s 3 -E -K -c clean" "${TIME_SECONDS}" 5 &
-    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -t 1000+ -m none -P FTP -D 10000 -q 4 -s 4 -E -K -c clean" "${TIME_SECONDS}" 5 &
-    wait
-  elif [ "${SUBJECT}" = "openssl" ]; then
-    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet out-"${SUBJECT}"-aflnet "-P TLS -D 10000 -q 3 -s 3 -E -K -R -W 100" "${TIME_SECONDS}" 5 &
-    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -P TLS -D 10000 -q 4 -s 4 -E -K -R -W 100" "${TIME_SECONDS}" 5 &
-    wait
-  elif [ "${SUBJECT}" = "openssh" ]; then
-    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet out-"${SUBJECT}"-aflnet "-P SSH -D 10000 -q 3 -s 3 -E -K -W 10" "${TIME_SECONDS}" 5 &
-    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -P SSH -D 10000 -q 4 -s 4 -E -K -W 10" "${TIME_SECONDS}" 5 &
-    wait
-  else
-    echo "Invalid subject: ${SUBJECT}"
-    exit 1
-  fi
+#  if [ "${SUBJECT}" = "lightftp" ]; then
+#    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet out-"${SUBJECT}"-aflnet "-P FTP -D 10000 -q 3 -s 3 -E -K -c ./ftpclean.sh" "${TIME_SECONDS}" 5 &
+#    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -P FTP -D 10000 -q 4 -s 4 -E -K -c ./ftpclean.sh" "${TIME_SECONDS}" 5 &
+#    wait
+#  elif [ "${SUBJECT}" = "proftpd" ]; then
+#    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet out-"${SUBJECT}"-aflnet "-t 1000+ -m none -P FTP -D 10000 -q 3 -s 3 -E -K -c clean" "${TIME_SECONDS}" 5 &
+#    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -t 1000+ -m none -P FTP -D 10000 -q 4 -s 4 -E -K -c clean" "${TIME_SECONDS}" 5 &
+#    wait
+#  elif [ "${SUBJECT}" = "openssl" ]; then
+#    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet out-"${SUBJECT}"-aflnet "-P TLS -D 10000 -q 3 -s 3 -E -K -R -W 100" "${TIME_SECONDS}" 5 &
+#    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -P TLS -D 10000 -q 4 -s 4 -E -K -R -W 100" "${TIME_SECONDS}" 5 &
+#    wait
+#  elif [ "${SUBJECT}" = "openssh" ]; then
+#    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet out-"${SUBJECT}"-aflnet "-P SSH -D 10000 -q 3 -s 3 -E -K -W 10" "${TIME_SECONDS}" 5 &
+#    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -P SSH -D 10000 -q 4 -s 4 -E -K -W 10" "${TIME_SECONDS}" 5 &
+#    wait
+#  else
+#    echo "Invalid subject: ${SUBJECT}"
+#    exit 1
+#  fi
   #TODO: Try some minimum examples
 #  echo "profuzzbench_exec_common.sh donggeliu/${SUBJECT} 4 ${RESULT_DIR} aflnet out-${SUBJECT}-aflnet ${AFLNET_OPTIONS} ${TIME_SECONDS} 5"
-#  profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet out-"${SUBJECT}"-aflnet ${AFLNET_OPTIONS} "${TIME_SECONDS}" 5 &
-  #profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "${LEGION_OPTIONS}" "${TIME_SECONDS}" 5 &
-  #wait
+  profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet out-"${SUBJECT}"-aflnet "${AFLNET_OPTIONS}" "${TIME_SECONDS}" 5 &
+  profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "${LEGION_OPTIONS}" "${TIME_SECONDS}" 5 &
+  wait
 else
-  # profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion ${AFLNET_OPTIONS} "${TIME_SECONDS}" 5
-  if [ "${SUBJECT}" = "lightftp" ]; then
-    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -P FTP -D 10000 -q 4 -s 4 -E -K -c ./ftpclean.sh" "${TIME_SECONDS}" 5 &
-    wait
-  elif [ "${SUBJECT}" = "proftpd" ]; then
-    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -t 1000+ -m none -P FTP -D 10000 -q 4 -s 4 -E -K -c clean" "${TIME_SECONDS}" 5 &
-    wait
-  elif [ "${SUBJECT}" = "openssl" ]; then
-    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -P TLS -D 10000 -q 4 -s 4 -E -K -R -W 100" "${TIME_SECONDS}" 5 &
-    wait
-  elif [ "${SUBJECT}" = "openssh" ]; then
-    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -P SSH -D 10000 -q 4 -s 4 -E -K -W 10" "${TIME_SECONDS}" 5 &
-    wait
-  else
-    echo "Invalid subject: ${SUBJECT}"
-    exit 1
-  fi
+   profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "${LEGION_OPTIONS}" "${TIME_SECONDS}" 5 &
+   wait
+#  if [ "${SUBJECT}" = "lightftp" ]; then
+#    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -P FTP -D 10000 -q 4 -s 4 -E -K -c ./ftpclean.sh" "${TIME_SECONDS}" 5 &
+#    wait
+#  elif [ "${SUBJECT}" = "proftpd" ]; then
+#    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -t 1000+ -m none -P FTP -D 10000 -q 4 -s 4 -E -K -c clean" "${TIME_SECONDS}" 5 &
+#    wait
+#  elif [ "${SUBJECT}" = "openssl" ]; then
+#    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -P TLS -D 10000 -q 4 -s 4 -E -K -R -W 100" "${TIME_SECONDS}" 5 &
+#    wait
+#  elif [ "${SUBJECT}" = "openssh" ]; then
+#    profuzzbench_exec_common.sh donggeliu/"${SUBJECT}" 4 "${RESULT_DIR}" aflnet_legion out-"${SUBJECT}"-aflnet_legion "-l 0 -p 5 -a -z -r 1.414 -P SSH -D 10000 -q 4 -s 4 -E -K -W 10" "${TIME_SECONDS}" 5 &
+#    wait
+#  else
+#    echo "Invalid subject: ${SUBJECT}"
+#    exit 1
+#  fi
 fi
 
 # Collect the results
